packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@prisma/engines'
  - 'prisma'
  - '@prisma/client'
  - '@clerk/shared'
  - '@nestjs/core'
  - '@parcel/watcher'
  - 'core-js'
  - 'core-js-pure'
  - 'unrs-resolver'
